config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :users
  resources :cities
  resources :rsvps

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/users/new', to: 'sessions#new'
  post '/users/new', to: 'sessions#create'

  delete '/login', to: 'sessions#destroy', as: :logout
  delete '/logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit'

  get '/events/home', to: 'users#home'
  #delete '/events', to: 'events#destroy', as: :delete_event

  root 'homepage#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :user_cities
  has_many :users, through: :user_city
  has_many :events

  validates :name, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :rsvps
  has_many :guests, :through => :rsvps, :source => :user
  belongs_to :city
  belongs_to :host, :class_name => "User"
  has_one_attached :avatar


  validates :name, presence: true
  validates :address, presence: true
  validates :date, presence: true
  validates :time, presence: true

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :guest, :class_name => "User"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :user_cities
  has_many :cities, through: :user_city
  has_many :rsvps, :foreign_key => :guest_id
  has_many :attended_events, through: :rsvps, :source => :event
  has_many :hosted_events, :foreign_key => :host_id, :class_name => "Event"
  has_one_attached :avatar


  validates :first_name, presence: true
  validates :email, uniqueness: true

end

app/models/user_city.rb
class UserCity < ApplicationRecord
  belongs_to :city
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user_city
  before_action :set_current_user

  def set_current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!@current_user
  end

  def current_user_city
    City.all.find do |city|
      city.id == @current_user.city_id
    end
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  before_action :set_city, only: [:show, :edit, :update]

  def index
    @cities = City.all
  end

  def show
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.valid?
      @city.save
      flash[:notice] = "Your city was successfully created."
      redirect_to @city
    else
      flash[:errors] = @city.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @city.update(city_params)
    if @city.valid?
      flash[:notice] = "Your city was successfully updated."
      redirect_to @city
    else
      flash[:errors] = @city.errors.full_messages
      render :edit
    end
  end

  def delete
  end

  private

  def set_city
    @city = City.find(params[:id])
  end

  def city_params
    params.require(:city).permit(:name, :state)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    if city_events == []
      @message = "There are currently no events in this city."
    else
      @events = city_events
    end
    @city = current_user_city
  end


  def show
    @rsvp = Rsvp.new
    @rsvps = Rsvp.all
    #byebug corresponds to lines 37-39 in show page
  end

  def new
    if logged_in?
      @event = Event.new
    else
      flash[:message] = "Please log in to create an event."
      redirect_to login_path
    end
  end

  def create
    @event = Event.create(event_params)
    @host = User.find_by(id: params[:event][:host_id])
    if @event.valid?
      flash[:notice] = "Your event was successfully created."
      redirect_to @event
    else
      flash[:errors] = @event.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    if @event.valid?
      flash[:notice] = "Your event was successfully updated."
      redirect_to @event
    else
      flash[:errors] = @event.errors.full_messages
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to @current_user
  end

  private

  def city_events
    Event.all.select do |event|
      event.city_id == @current_user.city_id
    end
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:avatar, :name, :date, :time, :description, :address, :city_id, :host_id)
  end

  # def find_attendees
  #   attendees = []
  #   Users.all.each do |user|
  #     user.id == @event.guests
  #   end
  # end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end
  
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  def new
  end

  def create
    Rsvp.create(rsvp_params)
    flash[:message] = "Successfully RSVP'd for this event."
    redirect_to @current_user
  end


  private

  def rsvp_params
    params.require(:rsvp).permit(:guest_id, :event_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to profile_path
    else
      flash[:message] = 'Invalid Login'
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:message] = "You have successfully logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :find_hosted_events, :find_attended_events
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    # if @current_user.id.to_i != params[:id].to_i
    #   redirect_to profile_path
    # end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.valid?
      flash[:notice] = "You have successfully updated your account."
      redirect_to '/profile'
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def delete
  end

  private

  def find_hosted_events
    Event.all.select do |event|
      if event.host_id == @current_user.id
        event
      end
    end
  end

  def find_attended_events
    rsvps = find_current_user_rsvps
    events = []
    Event.all.each do |event|
      if rsvps.find {|rsvp| event.id == rsvp.event_id}
        events << event
      end
    end
    return events
  end

  def find_current_user_rsvps
    Rsvp.all.select do |rsvp|
      if rsvp.guest_id == @current_user.id
        rsvp
      end
    end
  end

  def set_user
    @user = User.find(@current_user.id)
  end

  def user_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :email, :password, :city_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/edit.html.erb
<h1> Edit a City </h1>

<% if flash[:errors]%>
  <% flash[:errors].each do |message|%>
    <p style='color:red'><%= message%> </p>
  <%end%>
<%end%>

<%= form_for @city do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "State" %>
  <%= f.text_field :state %>
  <%= f.submit "Edit City" %>
<% end %>

app/views/cities/index.html.erb
<h1>Cities</h1>

<% @cities.each do |city|%>
  <li><%=link_to city.name, city_path(city) %></li>
<%end%>

app/views/cities/new.html.erb
<h1> Create a New City </h1>

<% if flash[:errors]%>
  <% flash[:errors].each do |error|%>
    <p style='color:red'><%= error%> </p>
  <%end%>
<%end%>

<%= form_for @city do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "State" %>
  <%= f.text_field :state %>
  <%= f.submit "Create City" %>
<% end %>

app/views/cities/show.html.erb
<h1><%=@city.name%></h1>

<%if flash[:notice]%>
  <%style= 'color:green'%>
  <%= flash[:notice] %>
<%end%>

app/views/events/edit.html.erb
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="center">
      <h1>Update Your Event</h1>
    </div>
  </div>
</div>

<div class="sub_title">
<%= form_for @event do |f|%>

  <div class="row">
    <div class="col-sm-3">
    <div class="form_fields_right"
      <br><br>
      <%= f.label "Event Name"%><br>
      <%= f.label :date%><br>
      <%= f.label :time%><br>
      <%= f.label :address%><br>
      <%= f.label "City"%><br>
      <%= f.label :description%><br><br>
      <%= f.label "Event Photo" %><br>
    </div>
    </div>

    <div class="col-sm-3">
    <div class="form_fields_left">
      <br><br>
      <%= f.text_field :name%><br><br>
      <%= f.date_select(:date)%><br><br>
      <%= f.time_select(:time)%><br><br>
      <%= f.text_field :address%><br><br>
      <%= f.collection_select :city_id, City.all, :id, :name%><br><br>
      <%= f.text_area :description%><br><br>
      <%= f.file_field :avatar %><br><br>
      <%= f.hidden_field :host_id, :value => @current_user.id %><br>
      <%= f.submit%>
    </div>
    </div>
    <%end%>

    <div class="col-sm-4">
      This is the third column.
    </div>
  </div>



<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
  <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/events">Events</a>
    </li>
  </ul>
</nav>

<div class="container-fluid"><br>
  
</div>
<br>
<br>
<br>
<br>

app/views/events/index.html.erb
<!-- <img src="https://www.heritageschoolofinteriordesign.com/main/wp-content/uploads/2018/05/103845788-_sites-default-files-images-103845788-GettyImages-155735310.1910x1000.jpg" alt="Seattle Skyline"/>
<%= image_tag("seattle.jpg", :alt => "seattle") %> -->

<header>
  <div class="overlay"></div>
  <img src="https://www.heritageschoolofinteriordesign.com/main/wp-content/uploads/2018/05/103845788-_sites-default-files-images-103845788-GettyImages-155735310.1910x1000.jpg" alt="Seattle Skyline"/>

  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-3">hey.></h1>
        <p class="lead mb-0">this is seattle.</p>
      </div>
    </div>
  </div>
</header>

<br>

<div class="title">
  <h1>Events in <%= @city.name %></h1>
</div>

<div class="sub_title">
<% if @events != nil %>
  <% @events.each do |event|%>
    <li>
      <%=link_to event.name, event%>
      (<%=event.date.strftime('%B %d, %Y')%> at <%=event.time.strftime('%I:%M %p')%>)
    </li>
  <%end%>
<%else %>
  <p> <%= @message %> </p>
<%end%>
</div>


<br>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
  <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/events">Events</a>
    </li>
  </ul>
  <div style="padding-left: 950px;">
    <a class="button" href="/events/new" role="button">
    Host New Event
    </a>
  </div>
</nav>

<div class="container-fluid"><br>
  </div>
<br>
<br>
<br>
<br>

app/views/events/new.html.erb
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="center">
      <h1>Create an Event!</h1>
    </div>
  </div>
</div>

<div class="sub_title">
<%= form_for @event do |f|%>

  <div class="row">
    <div class="col-sm-3">
    <div class="form_fields_right"
      <br><br>
      <%= f.label "Event Name"%><br>
      <%= f.label :date%><br>
      <%= f.label :time%><br>
      <%= f.label :address%><br>
      <%= f.label "City"%><br>
      <%= f.label :description%><br><br>
      <%= f.label "Event Photo" %><br>
    </div>
    </div>

    <div class="col-sm-3">
    <div class="form_fields_left">
      <br><br>
      <%= f.text_field :name%><br><br>
      <%= f.date_select(:date)%><br><br>
      <%= f.time_select(:time)%><br><br>
      <%= f.text_field :address%><br><br>
      <%= f.collection_select :city_id, City.all, :id, :name%><br><br>
      <%= f.text_area :description%><br><br>
      <%= f.file_field :avatar %><br><br>
      <%= f.hidden_field :host_id, :value => @current_user.id %><br>
      <%= f.submit%>
    </div>
    </div>
    <%end%>

    <div class="col-sm-4">
<<<<<<< HEAD
      
=======
    
>>>>>>> eefd7cccd5a7cecfa9fe64937db995eada4fe0c3
    </div>
  </div>
  <br>
  <br>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
    <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/profile">My Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/events">Events</a>
      </li>
    </ul>
  </nav>
<<<<<<< HEAD
=======

  <div class="container-fluid"><br>

  </div>
  <br>
  <br>
  <br>
  <br>
<<<<<<< HEAD
=======
>>>>>>> 337b5c773274d373dcf0744a39ed9a18e52a4cd8
>>>>>>> 279684ecc3c3192563f5db42b1ff7702604e591e
>>>>>>> eefd7cccd5a7cecfa9fe64937db995eada4fe0c3

app/views/events/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="center">
      <div class="padding">

    <h1><%= @event.name%></h1>

    <br><p>Hosted by: <b><%= @event.host.first_name %> <%= @event.host.last_name %></b></p>

    <p>This event will take place on <b><%= @event.date.strftime('%B %d, %Y')%></b> at <b><%= @event.time.strftime('%I:%M %p')%></b>.</p>

    <p>Location: <b><%= @event.address%></b></p>

    <p><%= @event.description %></p>



    <%= form_for @rsvp do |f| %>
        <%= f.hidden_field :guest_id, :value => @current_user.id %>
        <%= f.hidden_field :event_id, :value => @event.id %>
        <%= f.submit "RSVP" %>
    <%end%>

    <br>
    <% if @event.host_id == @current_user.id %>
      <a class="button" href="/events/<%=@event.id%>" data-method="delete" role="button">
        Delete This Event
      </a>
      <a class="button" href="/events/<%=@event.id%>/edit" role="button">
        Edit This Event
      </a>
    <%end%>

    <% if @rsvps.find {|rsvp| @current_user.id == rsvp.guest_id} %>

    <% else%>
      
    <%end%>


  </div>
  </div>
  </div>


  <div class="col-sm-5">
    <div class="center">
    <br><br>
    <% if @event.avatar.attached? %>
      <image src='<%=(url_for(@event.avatar))%>'class="rounded" style="display:inline"  height="300">
    <%end%>
    </div>
  </div>
</div>





<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
  <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/events">Events</a>
    </li>
  </ul>
  <div style="padding-left: 950px;">
    <a class="button" href="/events/new" role="button">
    Host New Event
    </a>
  </div>
</nav>


<br>
<br>
<br>
<br>

app/views/homepage/index.html.erb
<!-- credit for snippet below: https://startbootstrap.com/snippets/video-header/ -->
<br>
<br>
<div class="jumbotron">

  <header>
    <div class="overlay"></div>
    <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
      <source src="https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4" type="video/mp4"> -->
    </video>
    <div class="container h-100">
      <div class="d-flex h-100 text-center align-items-center">
        <div class="w-100 text-white">
          <h1 class="display-3">CityExplorer</h1>
          <p class="lead mb-0">Explore A New City Today</p>
        </div>
      </div>
    </div>
  </header>

  <section class="my-5">
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
        </div>
      </div>
    </div>
  </section>

  <h1 class="display-4">Welcome to CityExplorer</h1>
  <p class="lead">Find events in your city and meet new friends!</p>
  <hr class="my-4">

  <%if !@current_user%>
    <a class="button" href="/users/new" role="button">Sign Up</a>
    <a class="button" href="/login" role="button">Login</a>
  <%else%>
    <a class="button" href="/profile" role="button"> My Profile</a>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Module2FinalProject</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
          <nav class="navbar navbar-dark bg-dark">
            <!-- "navbar navbar-dark bg-dark" option for class -->
            <!-- "navbar navbar-light bg-light" option for class -->
            <!-- "navbar navbar-light" style="background-color: #e3f2fd;" -->

      <a class="navbar-brand" href="/">
        <img src="https://i.ibb.co/gvJN3Rz/Logo-Makr-6-Nnh-BW.png" alt="Logo-Makr-6-Nnh-BW" border="0" height="50">
      </a>
      <form class="form-inline">
      <div style="padding-left: 10px;">
        <a class="button" href="/logout" data-method="delete" role="button">
        Logout
        </a>
      </div>
      </form>
      </nav>
      <br>







    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="center">
      <h1> Update Your Account </h1>
    </div>
  </div>
</div>

<% if flash[:errors]%>
  <% flash[:errors].each do |message|%>
    <p style='color:red'><%= message%> </p>
  <%end%>
<%end%>

<%= form_for @user do |f| %>

<div class="row">
  <div class="col-sm-3">
  <div class="form_fields_right"

    <br><br>
    <%= f.label "First Name" %><br>
    <%= f.label "Last Name" %><br>
    <%= f.label "Email" %><br>
    <%= f.label "password" %><br>
    <%= f.label "City"%><br>
    <%= f.label "Profile Photo" %><br>
    <br>
  </div>
  </div>

  <div class="col-sm-3">
  <div class="form_fields_left">
    <br><br>
    <%= f.text_field :first_name %><br><br>
    <%= f.text_field :last_name %><br><br>
    <%= f.text_field :email %><br><br>
    <%= f.password_field :password %><br><br>
    <%= f.collection_select :city_id, City.all, :id, :name%><br><br>
    <%= f.file_field :avatar %><br><br>
  </div>
  </div>

</div>
</div>

<div class="row">
  <div class="col-sm-6">
  <div class="center">
    <%= f.submit "Update Account" %><br>
    <br>
    <br>
  </div>
  </div>
</div>

<% end %>


<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
  <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/events">Events</a>
    </li>
  </ul>
</nav>


<br>
<br>
<br>
<br>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user|%>
  <li><%=link_to user.first_name, user_path(user) %></li>
<%end%>


<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
  <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/events">Events</a>
    </li>
  </ul>
</nav>

<div class="container-fluid"><br>
  <h3>CityExplorer</h3>
  <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
  <h1>Scroll this page to see the effect</h1>
</div>
<br>
<br>
<br>
<br>

app/views/users/new.html.erb
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="center">
      <h1> Create a User Account </h1>
    </div>
  </div>
</div>

<% if flash[:errors]%>
  <% flash[:errors].each do |message|%>
    <p style='color:red'><%= message%> </p>
  <%end%>
<%end%>

<%= form_for @user do |f| %>

<div class="row">
  <div class="col-sm-3">
  <div class="form_fields_right"

    <br><br>
    <%= f.label "First Name" %><br>
    <%= f.label "Last Name" %><br>
    <%= f.label "Email" %><br>
    <%= f.label "password" %><br>
    <%= f.label "City"%><br>
    <%= f.label "Profile Photo" %><br>
    <br>
  </div>
  </div>

  <div class="col-sm-3">
  <div class="form_fields_left">
    <br><br>
    <%= f.text_field :first_name %><br><br>
    <%= f.text_field :last_name %><br><br>
    <%= f.text_field :email %><br><br>
    <%= f.password_field :password %><br><br>
    <%= f.collection_select :city_id, City.all, :id, :name%><br><br>
    <%= f.file_field :avatar %><br><br>
  </div>
  </div>

</div>
</div>

<div class="row">
  <div class="col-sm-6">
  <div class="center">
    <%= f.submit "Create Account" %><br>
    <br>
    <br>
    <h4>Already have an account? Login <%=link_to "here", login_path %></h4>
  </div>
  </div>
</div>

<% end %>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
  <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/events">Events</a>
    </li>
  </ul>
</nav>

<div class="container-fluid"><br>
  <h3>CityExplorer</h3>
  <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
  <h1>Scroll this page to see the effect</h1>
</div>
<br>
<br>
<br>
<br>

app/views/users/show.html.erb
<header>
  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4" type="video/mp4">
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-3">Welcome back, <%= @user.first_name %></h1>
        <p class="lead mb-0">We missed you.</p>
      </div>
    </div>
  </div>
</header>




<br>
<h2 class="title">Check out local events</h2>
<p class="sub_title">Link at the bottom of the page.</p>
<br>
<br>
<div class="row">
  <div class="col-sm-3">
    <div class="center">
      <% if @user.avatar.attached? %>
      <image src="<%=(url_for(@user.avatar))%>" class="rounded-circle" style="display:inline"  height="250">
      <%end%>
      <p style="font-size:40px"><%=@user.first_name%> <%=@user.last_name%></p>
      <a class="button" href="profile/edit" role="button">
        Edit Profile
      </a>

    </div>
  </div>

  <div class="col-sm-6">
    <div class="center">
      <h2> Events You are Scheduled to Attend </h2>
      <div class="list_main">

      <% find_attended_events.each do |event| %>
        <li>
          <%= link_to event.name, event %> (<%=event.date.strftime('%B %d, %Y')%>)
        </li>
      <% end %>
    </div>
    </div>

  </div>
  <div class="col-sm-3">
    <div class="list_side">
    <h4> My Hosted Events </h4>
    <% find_hosted_events.each do |event| %>
      <li>
        <%= link_to event.name, event %>
      </li>
    <% end %>
    </div>
  </div>
</div>




<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
  <a class="navbar-brand" href="/"><img src="https://i.ibb.co/2sJQTNR/Logo-Makr-39-Xboe.png" alt="Logo-Makr-39-Xboe" border="0" height="40"></a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/events">Events</a>
    </li>
  </ul>
  <div style="padding-left: 950px;">
    <a class="button" href="/events/new" role="button">
    Host New Event
    </a>
  </div>
</nav>

<div class="container-fluid"><br>

</div>
<br>
<br>
<br>
<br>